---
- hosts: 172.31.24.53
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myvariable1

    # Here register is key work not a variable.

  - name: i want to display first task result.
    debug:
      msg: "{{myvariable1}}"