---
- hosts: 172.31.24.232
  become: yes
  tasks:
  - include_tasks: myfile1.yml
  - name: Installing webserver apache2
    apt:
      name: apache2
      state: present
  - name: already created myindex.html , copying into node side.
    copy:
      src: myindex.html
      dest: /var/www/html/index.html