---
- hosts: 172.31.24.232
  become: yes
  tasks:
  - include_tasks: myfile1.yml
  - name: Installing webserver apache2
    apt:
      name: apache2
      state: present
  - name: already created myindex.html , copying into node side.
    copy:
      src: myindex1.html
      dest: /var/www/html/index.html
  - name: copy myindex.j2 file into nodes side
    copy:
      src: myindex.j2
      dest: /var/www/html/index.html