--- 
- hosts: all
  become: yes
  tasks:
  - name: Install webserver apache2 on Ansible Nodes
    apt:
     name: apache2
     state: present
  - name: Start webserver apache2 service on Ansible Nodes
    service:
     name: apache2
     state: started